kdp/urls.py
from django.urls import path

from .views import base_views, introduction_views, question_views, answer_views, vote_views, \
company_views, contact_views, client_views, client_answer_views, \
receive_views, privacy_views, email_views

app_name = 'kdp'

urlpatterns = [
    # base_views.py
    path('',
         base_views.index, name='index'),

    # privacy_views.py
    path('legal_kdp/',
         privacy_views.kdp_privacy_policy, name='kdp_privacy_policy'),
     path('legal_korea/',
         privacy_views.korea_privacy_policy, name='korea_privacy_policy'),

    # email_views.py
    path('email/', email_views.email, name='email'),

    # introduction_views.py
    path('introduction/', introduction_views.introduction, name='introduction'),

    # company_views.py
    path('company/', company_views.company, name='company'),

    # contact_views.py
    path('contact/', contact_views.contact, name='contact'),

    # client_views.py
    path('client/', client_views.client, name='client'),
    path('client/<int:client_id>/',
         client_views.client_detail, name='client_detail'),
    path('client/create/',
         client_views.client_create, name='client_create'),
    path('client/modify/<int:client_id>/',
         client_views.client_modify, name='client_modify'),
    path('client/delete/<int:client_id>/',
         client_views.client_delete, name='client_delete'),

    # receive_views.py
    path('receive/', receive_views.receive, name='receive'),


    # question_views.py
    path('question/', question_views.question, name='question'),
    path('question/<int:question_id>/',
         question_views.detail, name='detail'),
    path('question/create/',
         question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/',
         question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/',
         question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/',
         answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/',
         answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',
         answer_views.answer_delete, name='answer_delete'),


    # client_answer_views.py
    path('client_answer/create/<int:client_id>/',
         client_answer_views.client_answer_create, name='client_answer_create'),
    path('client_answer/modify/<int:client_answer_id>/',
         client_answer_views.client_answer_modify, name='client_answer_modify'),
    path('client_answer/delete/<int:client_answer_id>/',
         client_answer_views.client_answer_delete, name='client_answer_delete'),

# vote_views.py
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),
]

kdp/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from django.shortcuts import reverse


class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_question')
    group = models.ForeignKey(Group, on_delete=models.CASCADE, null=True)

    class Meta:
        permissions = [
            ('can_publish', 'Can Publish Posts'),
            ('can_change', 'Can Change Posts'),
            ('can_view', 'Can View Posts'),
            ('can_delete', 'Can Delete Posts'),
        ]
    def __str__(self):
        return self.subject

    def get_absolute_url(self):
        return reverse("kdp:question_list", kwargs={"pk": self.pk})


class Client(models.Model):
    email = models.EmailField()
    name = models.CharField(max_length=100)
    position = models.CharField(max_length=100)
    company = models.CharField(max_length=100)
    nation = models.CharField(max_length=100)
    phone = models.CharField(max_length=30)
    content = models.TextField()
    agree = models.CharField(max_length=1)
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.email
    
    # def __init__(self):
    #     if check_something():
    #         self.fields['agree'].initial  = True


# class Settings(models.Model):
#     receive_newsletter = models.BooleanField()



class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_answer')

    class Meta:
        permissions = [
            ('can_publish', 'Can Publish Posts'),
            ('can_change', 'Can Change Posts'),
            ('can_view', 'Can View Posts'),
            ('can_delete', 'Can Delete Posts'),
        ]

    def __str__(self):
        return self.content

    def get_absolute_url(self):
        return reverse("kdp:question_detail", kwargs={"pk": self.pk})


class ClientAnswer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_clientanswer')
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

    class Meta:
        permissions = [
            ('can_publish', 'Can Publish Posts'),
            ('can_change', 'Can Change Posts'),
            ('can_view', 'Can View Posts'),
            ('can_delete', 'Can Delete Posts'),
        ]

    def __str__(self):
        return self.content

    def get_absolute_url(self):
        return reverse("kdp:client_detail", kwargs={"pk": self.pk})

kdp/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseNotAllowed
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import AnswerForm
from ..models import Question, Answer

@login_required(login_url='common:login')
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user  # author 속성에 로그인 계정 저장
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('kdp:detail', question_id=question.id), answer.id))
    else:
        return HttpResponseNotAllowed('Only POST is possible.')
    context = {'question': question, 'form': form}
    return render(request, 'kdp/question_detail.html', context)

@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('kdp:detail', question_id=answer.question.id)
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('kdp:detail', question_id=answer.question.id), answer.id))
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'kdp/answer_form.html', context)

@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        answer.delete()
    return redirect('kdp:detail', question_id=answer.question.id)

@login_required(login_url='common:login')
def answer_vote(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user == answer.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        answer.voter.add(request.user)
    return redirect('{}#answer_{}'.format(
                resolve_url('kdp:detail', question_id=answer.question.id), answer.id))

kdp/views/base_views.py
from django.shortcuts import render
import logging

logger = logging.getLogger(__name__)

def index(request):
    logger.info("INFO 레벨로 출력")
    return render(request, 'kdp/index.html')



# import socket
# def index(request):
#     logger.info("INFO 레벨로 출력")
#     sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
#     sock.connect(("kdigitalpark.kr", 443))
#     sockname = sock.getsockname()[0]
#     context = {"Inner": sockname}
#     return render(request, 'kdp/index.html', context)

kdp/views/client_answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseNotAllowed
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import ClientAnswerForm
from ..models import Client, ClientAnswer, User

@login_required(login_url='common:login')
def client_answer_create(request, client_id):
    client = get_object_or_404(Client, pk=client_id)
    if request.method == "POST":
        form = ClientAnswerForm(request.POST)
        if form.is_valid():
            client_answer = form.save(commit=False)
            client_answer.author = request.user  # author 속성에 로그인 계정 저장
            client_answer.create_date = timezone.now()
            client_answer.client = client
            client_answer.save()
            return redirect('{}#client_answer_{}'.format(
                resolve_url('kdp:client_detail', client_id=client.id), client_answer.id))
    else:
        return HttpResponseNotAllowed('Only POST is possible.')
    context = {'client': client, 'form': form}
    return render(request, 'kdp/client_detail.html', context)

@login_required(login_url='common:login')
def client_answer_modify(request, client_answer_id):
    client_answer = get_object_or_404(ClientAnswer, pk=client_answer_id)
    if request.user != client_answer.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('kdp:client_detail', client_id=client_answer.client.id)
    if request.method == "POST":
        form = ClientAnswerForm(request.POST, instance=client_answer)
        if form.is_valid():
            client_answer = form.save(commit=False)
            client_answer.modify_date = timezone.now()
            client_answer.save()
            return redirect('{}#client_answer_{}'.format(
                resolve_url('kdp:client_detail', client_id=client_answer.client.id), client_answer.id))
    else:
        form = ClientAnswerForm(instance=client_answer)
    context = {'client_answer': client_answer, 'form': form}
    return render(request, 'kdp/clientanswer_form.html', context)

@login_required(login_url='common:login')
def client_answer_delete(request, client_answer_id):
    client_answer = get_object_or_404(ClientAnswer, pk=client_answer_id)
    if request.user != client_answer.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        client_answer.delete()
    return redirect('kdp:client_detail', client_id=client_answer.client.id)

kdp/views/client_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.core.paginator import Paginator
from django.db.models import Q, Count
from django.contrib.auth.models import User
from ..forms import ClientForm
from ..models import Client

# 고객 상담 문의
def contact(request):
    return render(request, 'kdp/client_form.html')


# 고객 상담 문의 목록 출력
@login_required(login_url='common:login')
def client(request):
    # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    so = request.GET.get('so', 'recent')  # 정렬기준
    # 정렬
    if so == 'popular':
        client_list = Client.objects.annotate(num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else:  # recent
        client_list = Client.objects.order_by('-create_date')
    # 검색
    if kw:
        client_list = client_list.filter(
            Q(email__icontains=kw) |  # 제목 검색
            Q(company__icontains=kw) |  # 회사 검색
            Q(content__icontains=kw)  # 문의 내용 검색
        ).distinct()
    # 페이징처리
    paginator = Paginator(client_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'client_list': page_obj, 'page': page, 'kw': kw}
    return render(request, 'kdp/client_list.html', context)


# Bulletin Board 상세내용 출력
@login_required(login_url='common:login')
def client_detail(request, client_id):
    client = get_object_or_404(Client, pk=client_id)
    context = {'client': client}
    return render(request, 'kdp/client_detail.html', context)


# Client 문의 접수 완료 화면
def client_receive(request):
    return render(request, 'kdp/client_receive.html')


# Client 문의 등록
def client_create(request):
    if request.method == 'POST':
        form = ClientForm(request.POST)
        # form1 = SettingsForm(request.POST)
        if form.is_valid():
            client = form.save(commit=False)
            # selected = form1.save(commit=False)
            client.create_date = timezone.now()
            client.save()
            # selected = request.POST.getlist('selected')
            # selected.save()
            return redirect('kdp:receive')
    else:
        form = ClientForm()
    context = {'form': form} #,'form1': form1}
    return render(request, 'kdp/client_form.html', context)


# Client Board 질문 수정
@login_required(login_url='common:login')
def client_modify(request, client_id):
    client = get_object_or_404(Client, pk=client_id)
    if request.user != client.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('kdp:client_detail', client_id=client.id)
    if request.method == "POST":
        form = ClientForm(request.POST, instance=client)
        if form.is_valid():
            client = form.save(commit=False)
            client.modify_date = timezone.now()  # 수정일시 저장
            client.save()
            return redirect('kdp:client_detail', client_id=client.id)
    else:
        form = ClientForm(instance=client)
    context = {'form': form}
    return render(request, 'kdp/client_form.html', context)


# Bulletin Board 질문 삭제
@login_required(login_url='common:login')
def client_delete(request, client_id):
    client = get_object_or_404(Client, pk=client_id)
    if request.user != client.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('kdp:client_detail', client_id=client.id)
    client.delete()
    return redirect('kdp:client')

kdp/views/company_views.py
from django.shortcuts import render
import logging
logger = logging.getLogger('kdp')

def company(request):
    logger.info("INFO 레벨로 출력")
    return render(request, 'kdp/company.html')

kdp/views/contact_views.py
from django.shortcuts import render
import logging
logger = logging.getLogger('kdp')

def contact(request):
    logger.info("INFO 레벨로 출력")
    return render(request, 'kdp/contact.html')

kdp/views/introduction_views.py
from django.shortcuts import render
import logging
logger = logging.getLogger('kdp')

def introduction(request):
    logger.info("INFO 레벨로 출력")
    return render(request, 'kdp/introduction.html')

kdp/views/privacy_views.py
from django.shortcuts import render
import logging
logger = logging.getLogger(__name__)

def kdp_privacy_policy(request):
    logger.info("INFO 레벨로 출력")
    return render(request, 'kdp/kdp_privacy_policy.html')

def korea_privacy_policy(request):
    logger.info("INFO 레벨로 출력")
    return render(request, 'kdp/korea_privacy_policy.html')

kdp/views/receive_views.py
from django.shortcuts import render
import logging
logger = logging.getLogger('kdp')

def receive(request):
    logger.info("INFO 레벨로 출력")
    return render(request, 'kdp/receive.html')

kdp/views/vote_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect

from ..models import Question, Answer


# 질문 추천 등록
@login_required(login_url='common:login')
def vote_question(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user == question.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        question.voter.add(request.user)
    return redirect('kdp:detail', question_id=question.id)


# 답글 추천 등록
@login_required(login_url='common:login')
def vote_answer(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user == answer.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        answer.voter.add(request.user)
    return redirect('kdp:detail', question_id=answer.question.id)

templates/kdp/client_detail.html
{% extends 'base.html' %}
{% load kdp_filter %}
{% block content %}
<div class="container my-3">
    <div class="pt-3">
        <p class="pt-3"></p>
        <p class="pt-3"></p>
    </div>
    <!-- message 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
    <!-- 질문 -->
    <div class="card my-3">
        <div class="card-body">
            <p class="border-bottom py-2">회사명: {{ client.company }}</p>
            <p class="border-bottom py-2">이름: {{ client.name }}</p>
            <p class="border-bottom py-2">직책: {{ client.position }}</p>
            <p class="border-bottom py-2">전화번호: {{ client.phone }}</p>
            <p class="border-bottom py-2">이메일: {{ client.email }}</p>
        </div>
    </div> 
    <div class="card my-3">
        <div class="card-body">
            <div class="card-title"><strong>문의내용:</strong></div>
            <div class="card-text">{{ client.content|mark }}</div>
            <div class="d-flex justify-content-end">
                {% if client.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ client.modify_date }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ client.name }}</div>
                    <div>{{ client.create_date }}</div>
                </div>
            </div>
        </div>
    </div>
    <!-- 답변 -->
    <p class="border-bottom my-3 py-2">{{client.clientanswer_set.count}}개의 답변이 있습니다.</p>
    {% for clientanswer in client.clientanswer_set.all %}
    <a id="clientanswer_{{ clientanswer.id }}"></a>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text">{{ clientanswer.content|mark }}</div>
            <div class="d-flex justify-content-end">
                {% if clientanswer.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ clientanswer.modify_date }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ clientanswer.author.first_name }}</div>
                    <div>{{ clientanswer.create_date }}</div>
                </div>
            </div>
            <div class="my-3">
                {% if request.user == clientanswer.author %}
                <a href="{% url 'kdp:client_answer_modify' clientanswer.id  %}"
                    class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary "
                    data-uri="{% url 'kdp:client_answer_delete' clientanswer.id  %}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
    <a href="{% url 'kdp:client' %}" class="btn btn-primary" style="font-weight:bold"><i class="fas fa-list"></i>  목록으로</a>

    <!-- 답변 등록 -->
    <form action="{% url 'kdp:client_answer_create' client.id %}" method="post" class="my-3">
        {% csrf_token %}
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
              name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
// const recommend_elements = document.getElementsByClassName("recommend");
// Array.from(recommend_elements).forEach(function(element) {
//     element.addEventListener('click', function() {
//         if(confirm("정말로 추천하시겠습니까?")) {
//             location.href = this.dataset.uri;
//         };
//     });
// });
</script>
{% endblock %}

templates/kdp/email.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="container-fluid">
    <div class="p-3">
        <p class="p-3"></p>
        <p class="p-3"></p>
    </div>
    <div class="text-center">
        <form method='POST' action="https://mail.kdvalley.com/mail_api/token_sso" target="_blank">
            <input class="form-control" type="text" name="api_key" id="api_key" value="#kdp@1914!">
            <input class="form-control" type="text" name="host_domain" id="host_domain" value="kdvalley.com">
            <textarea class="form-control" name="data" id="data" disabled>{{ data }}</textarea>
            <input type="button" class="btn btn-primary" id="btnOK" value="Email"/>
        </form>
    </div>
    <div class="m-3 p-3 text-center">
        <a type="button" id="home" class="btn btn-primary" href="{% url 'kdp:index' %}">홈으로 가기</a>
    </div>
</div>
{% endblock %}

<!--{% block script %}-->
<!--<script>-->
<!--var token = "";-->
<!--function makeid()-->
<!--{-->
<!--	var text = "";-->
<!--	var possible = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";-->
<!--	for( var i=0; i < 40; i++ )-->
<!--		text += possible.charAt(Math.floor(Math.random() * possible.length));-->
<!--	return text;-->
<!--}-->

<!--$(function(){-->
<!--	token = makeid();-->
<!--	$("#data").val('{"cid": "{{ user.username }}", "MailToken":"' + token + '"}')-->
<!--});-->
<!--$(document).ready(function(){-->
<!--    $("#btnOK").bind("click", function(){-->
<!--        $.ajax({-->
<!--            type : "POST",-->
<!--            dataType : "json",-->
<!--            url : "https://mail.koreadigitalpark.com/mail_api/token_sso",-->
<!--            data : {-->
<!--                "api_key" : $("#api_key").val(),-->
<!--                "host_domain" : $("#host_domain").val(),-->
<!--                "data" : $("#data").val(),-->
<!--            },-->
<!--            success:function(data){-->
<!--                console.log(data);-->
<!--                var date = new Date();-->
<!--                date.setTime(date.getTime() + (10 * 1000));-->
<!--                $.cookie('MailToken' , token, {expires: date, path: "/", domain: ".도메인(kosekorea.co.kr)"});-->
<!--                window.open('https://mail.kdvalley.com/lw_api/token_sso/'+ token + '?return_url=%2Fwebmail%2Flists', 'MAIL', '');-->
<!--            },-->
<!--            error:function(e){-->
<!--                alert(e.responseText);-->
<!--            }-->
<!--        });-->
<!--    });-->
<!--    $("#btnOK").trigger("click");-->
<!--    $("#home").trigger("click");-->
<!--});-->
<!--</script>-->
<!--{% endblock %}-->

templates/kdp/question_detail.html
{% extends 'base.html' %}
{% load kdp_filter %}
{% block content %}
<div class="container my-3">
    <div class="pt-3">
        <p class="pt-3"></p>
        <p class="pt-3"></p>
    </div>
    <!-- message 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text">{{ question.content|mark }}</div>
            <div class="d-flex justify-content-end">
                {% if question.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ question.modify_date }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ question.author.first_name }}</div>
                    <div>{{ question.create_date }}</div>
                </div>
            </div>
            <div class="my-3">
                <a href="javascript:void(0)" data-uri="{% url 'kdp:vote_question' question.id  %}"
                    class="recommend btn btn-sm btn-outline-secondary"> 추천
                    <span class="badge rounded-pill bg-success">{{question.voter.count}}</span>
                </a>
                {% if request.user == question.author %}
                <a href="{% url 'kdp:question_modify' question.id  %}"
                    class="btn btn-sm btn-outline-secondary">수정</a>
                    <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                        data-uri="{% url 'kdp:question_delete' question.id  %}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>
    <!-- 답변 -->
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <a id="answer_{{ answer.id }}"></a>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text">{{ answer.content|mark }}</div>
            <div class="d-flex justify-content-end">
                {% if answer.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ answer.modify_date }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ answer.author.first_name }}</div>
                    <div>{{ answer.create_date }}</div>
                </div>
            </div>
            <div class="my-3">
                <a href="javascript:void(0)" data-uri="{% url 'kdp:vote_answer' answer.id  %}"
                   class="recommend btn btn-sm btn-outline-secondary"> 추천
                    <span class="badge rounded-pill bg-success">{{answer.voter.count}}</span>
                </a>
                {% if request.user == answer.author %}
                <a href="{% url 'kdp:answer_modify' answer.id  %}"
                    class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary "
                    data-uri="{% url 'kdp:answer_delete' answer.id  %}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}

    <a href="{% url 'kdp:question' %}" class="btn btn-primary" style="font-weight:bold"><i class="fas fa-list"></i>  목록으로</a>

    <!-- 답변 등록 -->
    <form action="{% url 'kdp:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
              name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
const recommend_elements = document.getElementsByClassName("recommend");
Array.from(recommend_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}