common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
# from django.conf.urls import url


app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('profile/<int:user_id>/', views.profile, name='profile'),
    path('password_reset/', views.MyPasswordResetView.as_view(), name='password_reset'),
    path('reset/<uidb64>/<token>/', views.MyPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('change_password/', views.change_password, name='change_password'),
    # path('password_change/', views.MyPasswordChangeView.as_view(), name='password_change'),
]

kdp/urls.py
from django.urls import path

from .views import base_views, introduction_views, question_views, answer_views, vote_views, \
company_views, contact_views, client_views, client_answer_views, \
receive_views, privacy_views, email_views

app_name = 'kdp'

urlpatterns = [
    # base_views.py
    path('',
         base_views.index, name='index'),

    # privacy_views.py
    path('legal_kdp/',
         privacy_views.kdp_privacy_policy, name='kdp_privacy_policy'),
     path('legal_korea/',
         privacy_views.korea_privacy_policy, name='korea_privacy_policy'),

    # email_views.py
    path('email/', email_views.email, name='email'),

    # introduction_views.py
    path('introduction/', introduction_views.introduction, name='introduction'),

    # company_views.py
    path('company/', company_views.company, name='company'),

    # contact_views.py
    path('contact/', contact_views.contact, name='contact'),

    # client_views.py
    path('client/', client_views.client, name='client'),
    path('client/<int:client_id>/',
         client_views.client_detail, name='client_detail'),
    path('client/create/',
         client_views.client_create, name='client_create'),
    path('client/modify/<int:client_id>/',
         client_views.client_modify, name='client_modify'),
    path('client/delete/<int:client_id>/',
         client_views.client_delete, name='client_delete'),

    # receive_views.py
    path('receive/', receive_views.receive, name='receive'),


    # question_views.py
    path('question/', question_views.question, name='question'),
    path('question/<int:question_id>/',
         question_views.detail, name='detail'),
    path('question/create/',
         question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/',
         question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/',
         question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/',
         answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/',
         answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',
         answer_views.answer_delete, name='answer_delete'),


    # client_answer_views.py
    path('client_answer/create/<int:client_id>/',
         client_answer_views.client_answer_create, name='client_answer_create'),
    path('client_answer/modify/<int:client_answer_id>/',
         client_answer_views.client_answer_modify, name='client_answer_modify'),
    path('client_answer/delete/<int:client_answer_id>/',
         client_answer_views.client_answer_delete, name='client_answer_delete'),

# vote_views.py
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),
]

common/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    bio = models.TextField(null=True, blank=True)
    website_url = models.URLField(null=True, blank=True)


def on_post_save_for_user(sender, **kwargs):
    if kwargs['created']:
        user = kwargs['instance']
        Profile.objects.create(user=user)

# User 회원 가입 시 Profile 생성하기
post_save.connect(on_post_save_for_user, sender=settings.AUTH_USER_MODEL)

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "password1", "password2", "email")

common/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, update_session_auth_hash
from django.contrib.auth.views import PasswordChangeView, PasswordResetConfirmView, PasswordResetView
from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import render, redirect, resolve_url, HttpResponse, get_object_or_404
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from common.forms import UserForm


# 계정 생성
def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})


@login_required(login_url='common:login')
def profile(request, user_id):
    user = User.objects.get(id=user_id)
    groups = user.groups.all()
    context = {'groups': groups}
    return render(request, 'common/profile.html', context)


def page_not_found(request, exception):
    """
    404 Page not found
    """
    return render(request, 'common/404.html', {})


def internal_server_error(request, *args, **argv):
    """
    500 Internal Server Error
    """
    return render(request, 'common/500.html', status=500)


# class MyPasswordChangeView(PasswordChangeView):
#     success_url = reverse_lazy('common:profile')
#     template_name = 'common/password_change_form.html'
#
#     def form_valid(self, form):
#         messages.info(self.request, '암호변경을 완료했습니다.')
#         return super().form_valid(form)

@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('index')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'common/change_password.html', {
        'form': form
    })



class MyPasswordResetView(PasswordResetView):
    success_url = reverse_lazy('common:login')
    template_name = 'common/password_reset_form.html'
    email_template_name = 'common/password_reset.html'

    def form_valid(self, form):
        messages.info(self.request, '암호 변경 메일을 발송했습니다.')
        return super().form_valid(form)


class MyPasswordResetConfirmView(PasswordResetConfirmView):
    success_url = reverse_lazy('common:login')
    template_name = 'common/password_reset_confirm.html'

    def form_valid(self, form):
        messages.info(self.request, '암호 초기화를 완료했습니다.')
        return super().form_valid(form)

templates/common/change_password.html
{% extends "base.html" %}

{% block content %}
<h2 class="border-top m-3 p-3" style="text-align:center;">비밀번호 변경</h2>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form method="post" style="text-align:left;">
  {% csrf_token %}
    <div class="card m-3 p-3">
      <table>
          {{ form}}
      </table>
      <div class="text-center m-3 p-3" >
        <button type="submit">제출</button>
      </div>
    </div>
</form>
{% endblock %}

templates/common/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="pt-3">
        <p class="pt-3"></p>
        <p class="pt-3"></p>
    </div>
    <form method="post" action="{% url 'common:login' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">  <!-- 로그인 성공후 이동되는 URL -->
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

templates/common/password_change_form.html
{% extends "base.html" %}

{% block content %}
    <h2>암호변경</h2>
    <form action="" method="post">
        {% csrf_token %}
        <div class="card m-2 p-2">
            <table>
                {{ form.as_table }}
            </table>
            <div class="col-8 text-right">
                <input type="submit">
            </div>
        </div>
    </form>
{% endblock %}

templates/common/profile.html
{% extends "base.html" %}

{% block content %}
<div class="container my-3">
    <h3>{{ user.username }}'s Profile </h3>
    <div class="card my-3 p-3">
        <div class="card my-3 p-3">
            <h4>이름: {{ user.first_name|default:"&dash;" }} </h4>
        </div>
        <div class="card my-3 p-3">
            <h4>직책: {{ user.last_name|default:"&dash;" }} </h4>
        </div>
        <div class="card my-3 p-3">
            <h4>이메일: {{ user.email|default:"&dash;" }} </h4>
        </div>
        <div class="card my-3 p-3">
            <h4>그룹: {% for group in groups %} [ {{ group|default:"&dash;" }} ] {% endfor %}</h4>
        </div>
    </div>
    <div class="col-12 text-right">
        <a href="{% url 'common:change_password' %}">암호 변경하기</a>
    </div>
</div>
{% endblock %}

templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}