common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
# from django.conf.urls import url


app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('profile/<int:user_id>/', views.profile, name='profile'),
    path('password_reset/', views.MyPasswordResetView.as_view(), name='password_reset'),
    path('reset/<uidb64>/<token>/', views.MyPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('change_password/', views.change_password, name='change_password'),
    # path('password_change/', views.MyPasswordChangeView.as_view(), name='password_change'),
]

kdp/urls.py
from django.urls import path

from .views import base_views, introduction_views, question_views, answer_views, vote_views, \
company_views, contact_views, client_views, client_answer_views, \
receive_views, privacy_views, email_views

app_name = 'kdp'

urlpatterns = [
    # base_views.py
    path('',
         base_views.index, name='index'),

    # privacy_views.py
    path('legal_kdp/',
         privacy_views.kdp_privacy_policy, name='kdp_privacy_policy'),
     path('legal_korea/',
         privacy_views.korea_privacy_policy, name='korea_privacy_policy'),

    # email_views.py
    path('email/', email_views.email, name='email'),

    # introduction_views.py
    path('introduction/', introduction_views.introduction, name='introduction'),

    # company_views.py
    path('company/', company_views.company, name='company'),

    # contact_views.py
    path('contact/', contact_views.contact, name='contact'),

    # client_views.py
    path('client/', client_views.client, name='client'),
    path('client/<int:client_id>/',
         client_views.client_detail, name='client_detail'),
    path('client/create/',
         client_views.client_create, name='client_create'),
    path('client/modify/<int:client_id>/',
         client_views.client_modify, name='client_modify'),
    path('client/delete/<int:client_id>/',
         client_views.client_delete, name='client_delete'),

    # receive_views.py
    path('receive/', receive_views.receive, name='receive'),


    # question_views.py
    path('question/', question_views.question, name='question'),
    path('question/<int:question_id>/',
         question_views.detail, name='detail'),
    path('question/create/',
         question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/',
         question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/',
         question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/',
         answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/',
         answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',
         answer_views.answer_delete, name='answer_delete'),


    # client_answer_views.py
    path('client_answer/create/<int:client_id>/',
         client_answer_views.client_answer_create, name='client_answer_create'),
    path('client_answer/modify/<int:client_answer_id>/',
         client_answer_views.client_answer_modify, name='client_answer_modify'),
    path('client_answer/delete/<int:client_answer_id>/',
         client_answer_views.client_answer_delete, name='client_answer_delete'),

# vote_views.py
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),
]

kdp/views/base_views.py
from django.shortcuts import render
import logging

logger = logging.getLogger(__name__)

def index(request):
    logger.info("INFO 레벨로 출력")
    return render(request, 'kdp/index.html')



# import socket
# def index(request):
#     logger.info("INFO 레벨로 출력")
#     sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
#     sock.connect(("kdigitalpark.kr", 443))
#     sockname = sock.getsockname()[0]
#     context = {"Inner": sockname}
#     return render(request, 'kdp/index.html', context)

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/navbar.html
<!-- 네비게이션바 -->
<!--<nav class="navbar navbar-expand-lg bg-light fixed-top">-->
<nav class="navbar navbar-light navbar-expand-lg bg-light fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'index' %}">
            <img src="/static/img/kdv_new_logo_120_38.png" alt="" width="120" height="38" class="d-inline-block align-text-top">
    </a>
    <button class="navbar-toggler d-flex d-lg-none order-3 p-2" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasWithBothOptions" aria-controls="offcanvasWithBothOptions" aria-label="offcanvasWithBothOptionsLabel">
      <svg class="bi" width="24" height="24" aria-hidden="true">
        <use xlink:href="#three-dots"></use>
      </svg>
    </button>
    <div class="offcanvas offcanvas-end" data-bs-scroll="true" tabindex="-1" id="offcanvasWithBothOptions" aria-labelledby="offcanvasWithBothOptionsLabel">
      <div class="offcanvas-header">
        <a href="{% url 'index' %}" class="offcanvas-title" id="offcanvasWithBothOptionsLabel">
            <img src="/static/img/kdv_new_logo_2.png" width="350" height="47" class="d-inline-block align-text-top">
        </a>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-start flex-grow-1 pe-3">
          <li class="nav-item p-1">
            <a class="nav-link text-black" href="{% url 'kdp:introduction' %}" style="font-weight:bolder">KDV소개</a>
          </li>
          <li class="nav-item p-1">
            <a class="nav-link text-black" href="{% url 'kdp:company' %}" style="font-weight:bolder">회사소개</a>
          </li>
          <li class="nav-item p-1">
            <a class="nav-link text-black" href="{% url 'kdp:contact' %}" style="font-weight:bolder">연락처</a>
          </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item p-1">
            <a class="nav-link text-black" href="{% url 'kdp:client' %}" style="font-weight:bolder">고객문의</a>
          </li>
          <li class="nav-item p-1">
            <a class="nav-link text-black" href="{% url 'kdp:question' %}" style="font-weight:bolder">게시판</a>
          </li>
          {% endif %}
        </ul>
        <div class="pt-1">
          <ul class="navbar-nav mr-auto">
              {% if request.user.is_authenticated %}
              <li class="nav-item p-1">
                  <a href="https://kdvalley.com/kdp/email"
                     class="btn btn-sm btn-outline-secondary" target="_blank">이메일</a>
              </li>
              <li class="nav-item p-1">
                  <a href="{% url 'common:profile' user.id %}"
                     class="btn btn-sm btn-outline-secondary">마이페이지 [{{ user.username }}]</a>
              </li>
              <li class="nav-item p-1">
                  <a href="{% url 'common:logout' %}" class="btn btn-sm btn-outline-secondary">Logout</a>
              </li>
              {% else %}
              <li class="nav-item p-1">
                  <a href="{% url 'common:login' %}" class="btn btn-sm btn-outline-secondary">Login</a>
              </li>
              {% endif %}
          </ul>
        </div>
        </div>
      </div>
    </div>
</nav>

templates/navbar_old.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-sm navbar-light" style="background-color: white">
<div class="container-fluid">
    <a class="navbar-brand" href="{% url 'index' %}">
      <img src="/static/img/KDP_logo_bgremov.png" alt="" width="126" height="24" class="d-inline-block align-text-top">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav me-auto mb-2 mb-lg-0">
                <a class="nav-link" aria-current="page" href="{% url 'kdp:introduction' %}" style="font-weight:bolder">KDP소개</a>
                <a class="nav-link" href="{% url 'kdp:company' %}" style="font-weight:bolder">회사소개</a>
                <a class="nav-link" href="{% url 'kdp:contact' %}" style="font-weight:bolder">연락처</a>
                {% if request.user.is_authenticated %}
                <a class="nav-link" href="{% url 'kdp:client' %}" style="font-weight:bolder">고객문의</a>
                <a class="nav-link" href="{% url 'kdp:question' %}" style="font-weight:bolder">게시판</a>
                <a class="nav-link" href="https://mail.daum.net" style="font-weight:bolder" target="_blank">이메일</a>
                {% endif %}
            </div>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'common:profile' user.id %}"
                           class="btn btn-sm btn-outline-secondary">마이페이지 [{{ user.username }}]</a>
                        <a href="{% url 'common:logout' %}" class="btn btn-sm btn-outline-secondary">Logout</a>
                    {% else %}
                        <a href="{% url 'common:login' %}" class="btn btn-sm btn-outline-secondary">Login</a>
                    {% endif %}
                </li>
            </ul>
    </div>
</div>
</nav>